language: python
sudo: required
addons:
  apt:
    packages:
    - nvidia-384
    - nvidia-cuda-toolkit
    - nvidia-modprobe
script:
- sudo lspci -vvv | grep -A 15 3D
- sudo lshw -numeric -C display
- sudo dmesg | grep NVRM || echo NAH
